In [1]:
import pandas as pd

# Set list of experiment IDs you want to combine into a single CSV
experimentIds = ['cdswcsfi', 'gzrtcovy', 'lqqqlofw', 'sdmfwset', 'skdlqgrs', 'smkuypgb', 'twfcbrrg', 'vojtyqqj', 'wfxrueng', 'zjrrawxh', 'zjzlzmfc', ]

# Initialise dataframe for the result
column_names = ['Batch size', 'Memory per executor', 'Cores per executor', 'Total executor cores', 'Model', 'Wall clock','Start log', 'End log', 'Note']
df_all = pd.DataFrame(columns = column_names)

for ex in experimentIds:
    df = pd.read_csv(f'{ex}.csv', usecols=range(1,10), index_col=False)
    df_all = df_all.append(df, ignore_index=True)

,Batch size,Memory per executor,Cores per executor,Total executor cores,Model,Wall clock,Start log,End log,Note
0,64,2G,2.0,2.0,lenet5,386.985956314s,19:28:01,19:36:05,NaN
1,64,2G,2.0,2.0,lenet5,549.500197736s,19:36:08,19:47:01,NaN
2,64,2G,2.0,2.0,lenet5,617.160276408s,19:47:05,19:59:02,NaN
3,64,2G,2.0,2.0,lenet5,554.191634445s,19:59:05,20:10:11,NaN
4,64,2G,2.0,2.0,lenet5,514.66735543s,20:10:13,20:20:33,NaN

In [2]:
df_all.to_csv('all-experiments.csv')